<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net40;netstandard2.0</TargetFrameworks>
    <AssemblyName>SMBLibrary.Win32</AssemblyName>
    <Version>1.5.4</Version>
    <NoWarn>1573;1591</NoWarn>
    <RootNamespace>SMBLibrary.Win32</RootNamespace>
    <Authors>Tal Aloni</Authors>
    <Copyright>Copyright © Tal Aloni 2014-2025</Copyright>
    <PackageDescription>Windows specific extensions for SMBLibrary</PackageDescription>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/TalAloni/SMBLibrary</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TalAloni/SMBLibrary</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SMBLibrary\SMBLibrary.csproj" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(Configuration)' != 'Release'">
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'net40'">
    <PackageReference Include="NLog">
      <Version>5.4.0</Version>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="NLog">
      <Version>5.4.0</Version>
    </PackageReference>
  </ItemGroup>

</Project>
